-- Plano 3: Foco em Colunas de Alta Seletividade em JOINs
-- Objetivo: Indexar colunas com alta seletividade que são frequentemente usadas em JOINs

-- TB_TURMA
CREATE INDEX IDX_TURMA_DISCIPLINA ON TB_TURMA (ID_DISCIPLINA);
CREATE INDEX IDX_TURMA_SALA ON TB_TURMA (ID_SALA);

-- RL_TURMA_ALUNO
CREATE INDEX IDX_TURMA_ALUNO_TURMA ON RL_TURMA_ALUNO (ID_TURMA);
CREATE INDEX IDX_TURMA_ALUNO_ALUNO ON RL_TURMA_ALUNO (ID_ALUNO);

-- RL_DISCIPLINA_EQUIPAMENTO
CREATE INDEX IDX_DISCIPLINA_EQUIPAMENTO_DISCIPLINA ON RL_DISCIPLINA_EQUIPAMENTO (ID_DISCIPLINA);
CREATE INDEX IDX_DISCIPLINA_EQUIPAMENTO_EQUIPAMENTO ON RL_DISCIPLINA_EQUIPAMENTO (ID_EQUIPAMENTO);
