-- Plano 2: Foco em Colunas de Alta Seletividade em ORDER BY
-- Objetivo: Indexar colunas com alta seletividade que são frequentemente usadas em ORDER BY

-- TB_HORARIO
CREATE INDEX IDX_HORARIO_DIA_INICIO ON TB_HORARIO (CD_DIA_SEMANA, DH_INICIO);
CREATE INDEX IDX_HORARIO_INICIO ON TB_HORARIO (DH_INICIO);

-- TB_TURMA
CREATE INDEX IDX_TURMA_CODIGO ON TB_TURMA (CD_TURMA);

-- TB_DISCIPLINA
CREATE INDEX IDX_DISCIPLINA_CODIGO ON TB_DISCIPLINA (CD_DISCIPLINA);
