-- Plano 4: Equilíbrio entre WHERE, JOINs e ORDER BY
-- Objetivo: Indexar colunas com alta seletividade que são usadas em múltiplos contextos

-- TB_TURMA
CREATE INDEX IDX_TURMA_HORARIO_SALA ON TB_TURMA (ID_HORARIO, ID_SALA);
CREATE INDEX IDX_TURMA_CODIGO ON TB_TURMA (CD_TURMA);

-- TB_HORARIO
CREATE INDEX IDX_HORARIO_DIA_INICIO ON TB_HORARIO (CD_DIA_SEMANA, DH_INICIO);

-- RL_TURMA_ALUNO
CREATE INDEX IDX_TURMA_ALUNO_COMPOSTO ON RL_TURMA_ALUNO (ID_TURMA, ID_ALUNO);

-- TB_SALA
CREATE INDEX IDX_SALA_ACESSIVEL ON TB_SALA (IS_ACESSIVEL);
CREATE INDEX IDX_SALA_CAPACIDADE ON TB_SALA (QT_CAPACIDADE);

-- RL_DISCIPLINA_EQUIPAMENTO
CREATE INDEX IDX_DISCIPLINA_EQUIPAMENTO_DISCIPLINA ON RL_DISCIPLINA_EQUIPAMENTO (ID_DISCIPLINA);

-- RL_SALA_EQUIPAMENTO
CREATE INDEX IDX_SALA_EQUIPAMENTO_SALA ON RL_SALA_EQUIPAMENTO (ID_SALA);
