-- Plano 1: Foco em Colunas de Alta Seletividade em WHERE
-- Objetivo: Indexar colunas com alta seletividade que são frequentemente usadas em WHERE

-- TB_TURMA
CREATE INDEX IDX_TURMA_HORARIO ON TB_TURMA (ID_HORARIO);
CREATE INDEX IDX_TURMA_PROFESSOR ON TB_TURMA (ID_PROFESSOR);

-- TB_SALA
CREATE INDEX IDX_SALA_CAPACIDADE ON TB_SALA (QT_CAPACIDADE);
CREATE INDEX IDX_SALA_ACESSIVEL ON TB_SALA (IS_ACESSIVEL);

-- TB_ALUNO
CREATE INDEX IDX_ALUNO_DEFICIENCIA ON TB_ALUNO (IS_PESSOA_COM_DEFICIENCIA);
