-- Consulta de Disciplinas com Equipamentos
SELECT
    D.ID_DISCIPLINA,
    D.CD_DISCIPLINA,
    D.NO_DISCIPLINA,
    STRING_AGG (E.NO_EQUIPAMENTO, ', ') AS EQUIPAMENTOS_NECESSARIOS
FROM
    TB_DISCIPLINA D
    LEFT JOIN RL_DISCIPLINA_EQUIPAMENTO RDE ON D.ID_DISCIPLINA = RDE.ID_DISCIPLINA
    LEFT JOIN TB_EQUIPAMENTO E ON RDE.ID_EQUIPAMENTO = E.ID_EQUIPAMENTO
GROUP BY
    D.ID_DISCIPLINA,
    D.CD_DISCIPLINA,
    D.NO_DISCIPLINA
ORDER BY
    D.CD_DISCIPLINA;