-- Requisito 7.1: Consultar disciplinas com múltiplas turmas
SELECT 
    d.CD_DISCIPLINA,
    d.NO_DISCIPLINA,
    COUNT(t.ID_TURMA) as QT_TURMAS
FROM
    TB_DISCIPLINA d
    LEFT JOIN TB_TURMA t ON d.ID_DISCIPLINA = t.ID_DISCIPLINA
GROUP BY
    d.CD_DISCIPLINA,
    d.NO_DISCIPLINA
ORDER BY
    COUNT(t.ID_TURMA) DESC,
    d.CD_DISCIPLINA; 