-- Consulta de Disciplinas com Departamentos e Equipamentos
SELECT
    D.ID_DISCIPLINA,
    D.CD_DISCIPLINA,
    D.NO_DISCIPLINA,
    DP.NO_DEPARTAMENTO,
    STRING_AGG (E.NO_EQUIPAMENTO, ', ') AS EQUIPAMENTOS_NECESSARIOS
FROM
    TB_DISCIPLINA D
    LEFT JOIN RL_DISCIPLINA_DEPARTAMENTO RDD ON D.ID_DISCIPLINA = RDD.ID_DISCIPLINA
    LEFT JOIN TB_DEPARTAMENTO DP ON RDD.ID_DEPARTAMENTO = DP.ID_DEPARTAMENTO
    LEFT JOIN RL_DISCIPLINA_EQUIPAMENTO RDE ON D.ID_DISCIPLINA = RDE.ID_DISCIPLINA
    LEFT JOIN TB_EQUIPAMENTO E ON RDE.ID_EQUIPAMENTO = E.ID_EQUIPAMENTO
GROUP BY
    D.ID_DISCIPLINA,
    D.CD_DISCIPLINA,
    D.NO_DISCIPLINA,
    DP.NO_DEPARTAMENTO
ORDER BY
    D.CD_DISCIPLINA;