-- Requisito 7.2: Consultar todas as turmas de um aluno
SELECT
    a.NO_ALUNO,
    t.CD_TURMA,
    d.CD_DISCIPLINA,
    d.NO_DISCIPLINA,
    COUNT(rta2.ID_ALUNO) as QT_ALUNOS_TURMA
FROM
    TB_ALUNO a
    LEFT JOIN RL_TURMA_ALUNO rta ON a.ID_ALUNO = rta.ID_ALUNO
    LEFT JOIN TB_TURMA t ON rta.ID_TURMA = t.ID_TURMA
    LEFT JOIN TB_DISCIPLINA d ON t.ID_DISCIPLINA = d.ID_DISCIPLINA
    LEFT JOIN RL_TURMA_ALUNO rta2 ON t.ID_TURMA = rta2.ID_TURMA
GROUP BY
    a.NO_ALUNO,
    t.CD_TURMA,
    d.CD_DISCIPLINA,
    d.NO_DISCIPLINA
ORDER BY
    a.NO_ALUNO,
    d.CD_DISCIPLINA;
