-- Tabela de Horários
CREATE TABLE
    TB_HORARIO (
        ID_HORARIO SERIAL PRIMARY KEY,
        CD_DIA_SEMANA VARCHAR(20) NOT NULL,
        DH_INICIO TIME NOT NULL,
        DH_FIM TIME NOT NULL
    );

-- Tabela de Equipamentos
CREATE TABLE
    TB_EQUIPAMENTO (
        ID_EQUIPAMENTO SERIAL PRIMARY KEY,
        NO_EQUIPAMENTO VARCHAR(100) NOT NULL
    );

-- Tabela de Alunos
CREATE TABLE
    TB_ALUNO (
        ID_ALUNO SERIAL PRIMARY KEY,
        NO_ALUNO VARCHAR(100) NOT NULL,
        IS_PESSOA_COM_DEFICIENCIA BOOLEAN NOT NULL DEFAULT FALSE
    );

-- Tabela de Professores
CREATE TABLE
    TB_PROFESSOR (
        ID_PROFESSOR SERIAL PRIMARY KEY,
        NO_PROFESSOR VARCHAR(100) NOT NULL
    );

-- Tabela de Disciplinas
CREATE TABLE
    TB_DISCIPLINA (
        ID_DISCIPLINA SERIAL PRIMARY KEY,
        CD_DISCIPLINA VARCHAR(20) NOT NULL,
        NO_DISCIPLINA VARCHAR(100) NOT NULL
    );

-- Tabela de Salas
CREATE TABLE
    TB_SALA (
        ID_SALA SERIAL PRIMARY KEY,
        CD_SALA VARCHAR(20) NOT NULL,
        QT_CAPACIDADE INT NOT NULL,
        IS_ACESSIVEL BOOLEAN NOT NULL DEFAULT TRUE
    );

-- Tabela de Turmas
CREATE TABLE
    TB_TURMA (
        ID_TURMA SERIAL PRIMARY KEY,
        CD_TURMA VARCHAR(10) NOT NULL,
        ID_DISCIPLINA INTEGER NOT NULL,
        ID_HORARIO INTEGER NOT NULL,
        ID_PROFESSOR INTEGER,
        ID_SALA INTEGER NOT NULL,
        CONSTRAINT FK_TURMA_DISCIPLINA FOREIGN KEY (ID_DISCIPLINA) REFERENCES TB_DISCIPLINA (ID_DISCIPLINA),
        CONSTRAINT FK_TURMA_HORARIO FOREIGN KEY (ID_HORARIO) REFERENCES TB_HORARIO (ID_HORARIO),
        CONSTRAINT FK_TURMA_PROFESSOR FOREIGN KEY (ID_PROFESSOR) REFERENCES TB_PROFESSOR (ID_PROFESSOR),
        CONSTRAINT FK_TURMA_SALA FOREIGN KEY (ID_SALA) REFERENCES TB_SALA (ID_SALA)
    );