-- Consulta para visualizar os departamentos de cada professor
SELECT
    p.NO_PROFESSOR as Professor,
    d.NO_DEPARTAMENTO as Departamento
FROM
    TB_PROFESSOR p
    LEFT JOIN RL_DEPARTAMENTO_PROFESSOR rdp ON p.ID_PROFESSOR = rdp.ID_PROFESSOR
    LEFT JOIN TB_DEPARTAMENTO d ON d.ID_DEPARTAMENTO = rdp.ID_DEPARTAMENTO
ORDER BY
    p.NO_PROFESSOR,
    d.NO_DEPARTAMENTO; 